### ISSUE TITLE
Upgrade for Terraform 0.12

### ISSUE THREAD

**Issue by tlvenn** [secrethub/terraform-provider-secrethub#38]
Hi,

SecretHub TF provider needs to be upgraded for TF 0.12

Thanks in advance.

**Comment by tlvenn** [comment]
@SimonBarendse any idea when this task could be tackled ?

**Comment by florisvdg** [comment]
We're on it. You can expect to see a release this week.

**Comment by tlvenn** [comment]
Thanks for the update and great news !

**Comment by SimonBarendse** [comment]
Just released `v0.2.0` which adds Terraform `v0.12` support
