### ISSUE TITLE
Documentation: Terraform Cloud + IDE + Update

### ISSUE THREAD

**Issue by fabianriewe** [secrethub/terraform-provider-secrethub#90]
Hello, 
first of all I would like to thank you for this good product. We are using the terraform-provider for a few days now and everything is working fine. But there are a few things I like to mention, maybe this is helpful for improving the documentation.

1. To use the provider in Terraform cloud, install it with the following command and add the file to your vcs:
`mkdir -p ./.terraform/plugins/linux_amd64 && curl -SfL https://github.com/secrethub/terraform-provider-secrethub/releases/latest/download/terraform-provider-secrethub-linux-amd64.tar.gz | tar zxf - -C ./.terraform/plugins/linux_amd64
`
2. I am getting an unresolved error in my IDE when accessing a resources value. When using the datasource I am not getting any issues. For both resource and datasource the code is working fine but my IDE shows an unresolved error when accessing the `.value` . I am using PyCharm + Terraform Plugin as my IDE. 

3. I noticed that the documentation on the secret resource is outdated (https://secrethub.io/docs/reference/terraform/r/secret/). There is no information about the charset attribute

None of these 'issues' caused any trouble. The code was working fine with no errors.

**Comment by SimonBarendse** [comment]
Hi @fabianriewe, thanks for sharing your experiences! I'm glad to hear you like SecretHub and your feedback will definitely help us improve experience further.

Specifically I propose to do the following:

1. Update the Terraform provider installation documentation to include instructions on how to install on Terraform Cloud. Both in the [reference docs](https://secrethub.io/docs/reference/terraform/install/) as well as in the [guide](https://secrethub.io/docs/guides/terraform/#install).
2. I believe you might have found a bug in the [Terraform Plugin itself](https://github.com/VladRassokhin/intellij-hcl/). I'll investigate to confirm this hunch and report the issue upstream.
3. You're right. The [docs in this repository](https://github.com/secrethub/terraform-provider-secrethub/blob/v1.0.0/website/docs/r/secret.html.markdown) are updated to include the charset attribute, but it appears these changes haven't propagated to the https://secrethub.io website yet. I'll make sure the website is updated.

Did I get correctly that you can continue usage without any trouble in the meantime? Are these fixes urgent for you?

Thanks again for the feedback, it's definitely helpful :+1: If there's anything we can help with or if you have anything else to share, please let us know.

**Comment by SimonBarendse** [comment]
3. The docs on https://secrethub.io/docs/reference/terraform/r/secret/ are now up-to-date with the [docs in this repository](https://github.com/secrethub/terraform-provider-secrethub/blob/v1.0.0/website/docs/r/secret.html.markdown).

**Comment by fabianriewe** [comment]
Hi,
thank you so much for this quick response. None of these fixes are urgent. The code is working fine 👍
